algo: me

# General
n_generations: 1000
log_interval: 50
batch_size: 256

# Repertoire
repertoire_size: 2048
n_init_cvt_samples: 50_000

# GA emitter
iso_sigma: 0.005
line_sigma: 0.05
kernel_mutate: False
mutation_type: None
variation_percentage: 1

# Evaluation
fitness: neg_angle_var
descriptor:
  - pos_mass_avg
  - pos_linearvelocity_avg
descriptor_min: [0.0, 0.]
descriptor_max: [10., 0.5]
n_keep: 128
